### ISSUE TITLE
Missing dashoard "Hubble L7 HTTP metrics By Workload dashboard"

### ISSUE THREAD

**Issue by jxdn** [isovalent/cilium-grafana-observability-demo#2]
Hi, 

I ve been following the guide, so far is okay only i didnt get the HTTP Metrics dashboard. 

i only get the general dashboard for kubernetes

**Comment by tnorlin** [comment]
I believe it is in the details and that the cilium repo should be checked out at ec6a0d62d5dad43d5174605f4e32d220e85de429 in order to get the Hubble dashboards.

<img width="1016" alt="image" src="https://user-images.githubusercontent.com/23586614/198868135-7bdb5eec-9c5c-4e4f-8c6f-0d47c87eb4a2.png">

I (running om vm's and not kind) run wrong image tag in the cluster though, so my data isn't populating. With the cilium-ci:df6a89cdcc..-tag I only get image backoff's so changed to v1.13.0-rc1 - but that's probably wrong image so I cannot get data into the Hubble dashboard.

**Comment by chancez** [comment]
As @tnorlin said, the submodule needs to be checked out and it has the new dashboard. Additionally, you need to make sure you create the monitoring namespace before installing Cilium, or it will not be able to create the dashboard ConfigMap in the monitoring namespace for Grafana to pick up.

@tnorlin I've updated the image used to a newer tag, and opened #4 to track using a release tag once available.

**Comment by jxdn** [comment]
Thanks all
